In [1]:
array = [1, 2, 3, 4, 5]

boyut = len(array)

eleman_sayisi = sum(1 for i in array)

print("Arrayin boyutu:", boyut)
print("Arrayin eleman sayısı:", eleman_sayisi)

Arrayin boyutu: 5
Arrayin eleman sayısı: 5


In [23]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

array3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

boyut = array.ndim

boyut3d = array3d.ndim

eleman_sayisi = len(array)

eleman_sayisi3d = sum(len(satir) for satir in array3d)

satir_sayisi = 1

satir_sayisi3d = len(array3d)

sutun_sayisi = len(array)

sutun_sayisi3d = len(array3d)

print("Arrayin boyutu:", boyut)
print("Arrayin eleman sayısı:", eleman_sayisi)
print("Arrayin satır sayısı:", satir_sayisi)
print("Arrayin sütun sayısı:", sutun_sayisi)
print("Arrayin boyutu:", boyut3d)
print("Arrayin eleman sayısı:", eleman_sayisi3d)
print("Arrayin satır sayısı:", satir_sayisi3d)
print("Arrayin sütun sayısı:", sutun_sayisi3d)
print("Indexleme",array3d[-1])
print("Dilimleme",array[1:4])
print("1-2 satır ve 2-3 sütun",array[0:2, 1:3])

Arrayin boyutu: 2
Arrayin eleman sayısı: 2
Arrayin satır sayısı: 1
Arrayin sütun sayısı: 2
Arrayin boyutu: 3
Arrayin eleman sayısı: 6
Arrayin satır sayısı: 2
Arrayin sütun sayısı: 2
Indexleme [[10 11 12]
 [13 14 15]
 [16 17 18]]
Dilimleme [[4 5 6]]
1-2 satır ve 2-3 sütun [[2 3]
 [5 6]]


In [31]:
array_sifir = [[0] * 3 for i in range(3)]

array_bir = [[1] * 3 for i in range(3)]

array_birlesik = np.array(array_sifir) + np.array(array_bir)
array_birlesik2 = np.column_stack((array_sifir, array_bir))

print("Satır bazında birleştirilmiş array:")
print(array_birlesik)
print("Sütun bazında birleştirilmiş array:")
print(array_birlesik2)

Satır bazında birleştirilmiş array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Sütun bazında birleştirilmiş array:
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
